### ISSUE TITLE
Problem getting messages

### ISSUE THREAD

**Issue by rudignet** [pablo/huawei-modem-python-api-client#13]
Hello, when I try to get the list of sms with the method sms.get_sms always I receive only one, even if I set the qty to 20, the field count mark the total number of messages but the list of messages show only one, and not always the same, the box of both messages is the same, I think is a problem with the treatment of the response because using the web interface sms-list return an xml with all the messages..

Thank you

An Example:

{'type': 'response', 'response': {'Messages': {'Message': [{'Content': 'Test message', 'Sca': '', 'Priority': '0', 'Phone': '+34600123456', 'SaveType': '4', 'Smstat': '1', 'SmsType': '1', 'Index': '40000', 'Date': '2019-09-01 04:17:45'}]}, 'Count': '2'}}

**Comment by dopstar** [comment]
to upgrade:`pip install -U huawei-modem-api-client`

you can see more messages (if any) by setting the `qty` kwarg to a value greater 1 (the default). Also, by default the read sms'es are listed after all the unread sms'es have been listed. If you dont want that, set the `unread_preferred` kwarg to `False`.

example:

```python
huaweisms.api.sms.get_sms(ctx, qty=5, page=1, unread_preferred=False)
```

this returns the first 5 messages (ordered by date), read on unread.

**Comment by rudignet** [comment]
Thank you very much :)
