### ISSUE TITLE
router does not support http

### ISSUE THREAD

**Issue by mbadarneh1989** [pablo/huawei-modem-python-api-client#25]
B-315 router does not allow connection on port 80, only https (443). is there any way to solve this ?

**Comment by dopstar** [comment]
I will make a change to make the uri scheme configurable

**Comment by dopstar** [comment]
upgrade to version 1.1. which adds https support and is now in pypi (https://pypi.org/project/huawei-modem-api-client/). 

see the readme examples on how to use for https
