### ISSUE TITLE
add default timeout to get an exception by no response

### ISSUE THREAD

**Issue by kernelport** [pablo/huawei-modem-python-api-client#29]
if the modem is used over a longer period of time, it can happen that it does not respond anymore.
For this case a timeout would be useful to get an exception.
I implemented a default timeout of 30 s in 
 https://github.com/pablo/huawei-modem-python-api-client/blob/master/huaweisms/api/common.py
for the functions post_to_url and get_from_url .

**Comment by dopstar** [comment]
sounds great, please send the pull request

**Comment by dopstar** [comment]
addressed in https://github.com/pablo/huawei-modem-python-api-client/pull/30

upgrade to version 1.1.2 (or later) to use these changes
```bash
pip install 'huawei-modem-api-client>=1.1.2'
```
