### ISSUE TITLE
Remove hard deps on certifi and chardet

### ISSUE THREAD

**Issue by augustozanellato** [pablo/huawei-modem-python-api-client#43]
Hi,
In the project's `requirements.txt` there are hard dependencies on `certifi` and `chardet` on some old versions, those packages aren't used anywhere in the library, they're just indirect dependencies and are probably in requirements.txt because someone did a `pip freeze`.
At a quick glance a correct `requirements.txt` for this project would just be:
```
requests>=2.25.1
six>=1.15.0
typing>=3.7.4.3
```

**Comment by pablo** [comment]
Awesome,

Will take a look and update requirements.txt file.

Thanks!

**Comment by mkotek** [comment]
Implemented, so most likely the issue can be closed.

**Comment by augustozanellato** [comment]
> Implemented, so most likely the issue can be closed.

I don't see the needed changes on master branch.

EDIT: the wheel uploaded to PyPI for version 1.1.4 also doesn't have the fix

**Comment by dopstar** [comment]
@augustozanellato addressed this on this pr:
- https://github.com/pablo/huawei-modem-python-api-client/pull/45
pypi release 1.1.5 should be available within 10 min from now

**Comment by augustozanellato** [comment]
Thanks ^_^
